(define mary 1)
(define gabrielle 2)
(define lorna 3)
(define rosalind 4)
(define melissa 5)

(define (find-my-daughter)
  (let ((moore (amb mary gabrielle lorna rosalind melissa))
        (downing (amb mary gabrielle lorna rosalind melissa))
        (hall (amb mary gabrielle lorna rosalind melissa))
        (barnacle (amb mary gabrielle lorna rosalind melissa))
        (parker (amb mary gabrielle lorna rosalind melissa)))
    (require
      (distinct? (list moore downing hall barnacle parker))
      (= moore mary)
      (not (= barnacle gabrielle))
      (not (= hall rosalind))
      (not (= downing melissa))
      (= barnacle melissa))))
