(define (remove-first! array)
  (if (not (null? array)) ; '(x)
    (if (not (null? (cdr array))) ; '(x y z)
      (begin (set-car! array (cadr array)) ; '(y y z)
             (if (null? (cddr array)) ; (y y)
               (set-cdr! array '()) ; '(y)
               (remove-first! (cdr array))))
      (set-car! array '()))))

(define (remove-first!))
(define (remove! element array)
  (define (recur rest)
    (if (null? rest)
      '()
      (if (eq? element (car rest))
        (remove-first! rest)
        (recur (cdr rest)))))

  (recur array))
